--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/PJZ9n/FormAPI
branches:
- master
projects:
  FormAPI:
    path: ""
  libFormAPI:
    path: ""
    type: library
    model: virion
...
